name: Build & Publish Debug APK

on:
  push:
    branches:
      - master
      - fix/*
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Tests and Lint
        run: ./gradlew check
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: Generate version.txt for Hub release
        run: ./gradlew generateVersionTxt
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
